services:
  postgres:
    image: 'postgres:16.4'
    environment:
      - 'POSTGRES_DB=movie_api_db'
      - 'POSTGRES_PASSWORD=theSeniorDev'
      - 'POSTGRES_USER=root'
    ports:
      - '5431:5432'
