version: '3'

services:
  pgAdmin:
    image: dpage/pgadmin4
    ports: 
      - 80:80
    environment:
      PGADMIN_DEFAULT_EMAIL: bogdan@theseniordev.com
      PGADMIN_DEFAULT_PASSWORD: theSeniorDev
      PGADMIN_LISTEN_PORT: 80
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    links:
      - "database:db"
    volumes: 
      - ./.db/servers.json:/pgadmin4/servers.json
  database:
    # Official Postgres image from DockerHub (we use the last version)
    image: 'postgres:latest'
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root # The PostgreSQL user (useful to connect to the database)
      POSTGRES_PASSWORD: theSeniorDev # The PostgreSQL password (useful to connect to the database)
      POSTGRES_DB: movie_api_db # The PostgreSQL default database (automatically created at first launch)
    command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
    volumes: 
    - ./.db/postgres-data:/var/lib/postgresql/data
    # copy the sql script to create tables
    - ./.db/sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    # copy the sql script to fill tables
    - ./.db/sql/fill_tables.sql:/docker-entrypoint-initdb.d/fill_tables.sql
