server:
  port: 8080
  error:
    include-message: always
spring:
  datasource:
    url: jdbc:postgresql://localhost:5431/movie_api_db  # replace <your chosen database name>
    driver-class-name: org.postgresql.Driver
    username: root # adapt username accordingly
    # set PG_PASSWORD in your environment, e.g., by running "export PG_PASSWORD=<your chosen password" in the command line
    password: theSeniorDev
  jpa:
 #   database-platform: org.hibernate.dialect.PostgreSQLDialect
 #   generate-ddl: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: validate
    open-in-view: false
#  sql:
#    init:
#      mode: always
